## Handmade makefile (we cross our fingers to get compatibility? *)
## 10 / 09 / 2010

FOR_PACK= -for-pack Shared
INCLUDES =

include Makefile.files

CMO=$(MISC_CMO)
ML=$(MISC_SRC)

all: byte

include ../../Makefile.rules
