SOCIAL_SRC= miscXml.ml params.ml \
  time.ml period.ml \
  account_type.ml profile.ml storage.ml crop.ml tables.ml register.ml \
  \
  credentials.ml \
  \
  persistentFunctor.ml \
  datastoreFunctor.ml \
  paginate.ml \
  html_utils.ml \
  \
  ids.ml \
  \
  facebook.ml

SOCIAL_CMO=$(patsubst %.ml,%.cmo, $(SOCIAL_SRC))
SOCIAL_CMX=$(patsubst %.ml,%.cmx, $(SOCIAL_SRC))
