## Handmade makefile (we cross our fingers to get compatibility? *)
## 10 / 09 / 2010

FOR_PACK= -for-pack Shared
INCLUDES = -I ../misc

# cryptokit added for Security
include ../../Makefile.config
include Makefile.files

CMO=$(SOCIAL_CMO)
ML=$(SOCIAL_SRC)
all: byte

include ../../Makefile.rules
